version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/build
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user
  
hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 3000
      runas: ec2-user
