import Link from "next/link"
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className='Navbar'>
      <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 70 70" fill="none">
      <circle cx="35" cy="35" r="35" fill="#D9D9D9"/>
      <circle cx="35" cy="35" r="35" fill="#2D5DEB"/>
      </svg>
        <h className='Title_color'>   WAVE</h>
        <Link href={"/login"} className='NavBtn' style={{float : 'right'}}>LOGIN</Link>
        <Link href={"/contact"} className='NavBtn' style={{float : 'right'}}>CONTACT</Link>
      </div>

      <body className={inter.className}>{children}</body>
    </html>
  )
}

