name: Deploy

on:
  push: 
    branches:
      - main

env:
  S3_BUCKET_NAME: dongarimart
  CODE_DEPLOY_APPLICATION_NAME: dongarimart-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: dongarimart

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set env
        working-directory: ./
        run: |
          pwd
          touch .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}>>.env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}>>.env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }}>>.env
          echo EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}>>.env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}.env
          echo ADMIN_ID=${{ secrets.ADMIN_ID }}.env
          cat .env

      - name: Install Dependencies
        run: yarn install

      - name: Build next app
        run: yarn build

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash 

      - name: Configure AWS credentials
        uses: asw-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
      